apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gh-ghactions-quay-go-dthpecno-gitops
  description: This is GitOps manifest for gh-ghactions-quay-go-dthpecno   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=gh-ghactions-quay-go-dthpecno
    backstage.io/kubernetes-id: gh-ghactions-quay-go-dthpecno 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhopp-rhtap-testing/gh-ghactions-quay-go-dthpecno-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gh-ghactions-quay-go-dthpecno
